<?php

namespace Database\Seeders;

use App\Models\Disease;

use Illuminate\Database\Seeder;

class DiseaseSeeder extends Seeder
{
    public function run()
    {
        Disease::truncate();

        $data = [
            ['code' => '-', 'namaindo' => 'Reaksi gigitan serangga', 'namainggris' => 'Insect bite (kode tergantung lokasi)', ],
        	['code' => '-', 'namaindo' => 'Perdarahan saluran cerna bagian atas', 'namainggris' => 'Kode tergantung organ yang mengalami perdarahan', ],
        	['code' => '-', 'namaindo' => 'Perdarahan saluran cerna bagian bawah', 'namainggris' => 'Kode tergantung organ yang mengalami perdarahan', ],
        	['code' => '-', 'namaindo' => 'Fraktur terbuka, tertutup', 'namainggris' => 'Open fracture, close fracture', ],
        	['code' => 'A06.0-A06.1', 'namaindo' => 'Disentri basiler dan amuba', 'namainggris' => 'Acute amebic dysentery', ],
        	['code' => 'A09', 'namaindo' => 'Gastroenteritis (termasuk kolera, giardiasis)', 'namainggris' => 'Infectious gastroenteritis and colitis, unspecified', ],
        	['code' => 'A15.0', 'namaindo' => 'Tuberkulosis paru tanpa komplikasi', 'namainggris' => 'Tuberculosis of lung', ],
        	['code' => 'A27', 'namaindo' => 'Leptospirosis (tanpa komplikasi)', 'namainggris' => 'Leptospirosis', ],
        	['code' => 'A30', 'namaindo' => 'Lepra', 'namainggris' => 'Leprosy [Hansen’s disease]', ],
        	['code' => 'A35', 'namaindo' => 'Tetanus', 'namainggris' => 'Other tetanus', ],
        	['code' => 'A53.9', 'namaindo' => 'Sifilis stadium 1 dan 2', 'namainggris' => 'Syphilis', ],
        	['code' => 'A54', 'namaindo' => 'Gonore', 'namainggris' => 'Gonococcal infection', ],
        	['code' => 'A82', 'namaindo' => 'Rabies', 'namainggris' => 'Rabies', ],
        	['code' => 'A90-A91', 'namaindo' => 'Demam dengue, DHF Demam tifoid', 'namainggris' => 'Dengue hemorrhagic fever', ],
        	['code' => 'B00', 'namaindo' => 'Herpes simpleks tanpa komplikasi', 'namainggris' => 'Herpes simplex infections', ],
        	['code' => 'B01.9', 'namaindo' => 'Varisela tanpa komplikasi', 'namainggris' => 'Varicella without complication', ],
        	['code' => 'B02', 'namaindo' => 'Herpes zoster tanpa komplikasi', 'namainggris' => 'Herpes zoster', ],
        	['code' => 'B05.9', 'namaindo' => 'Morbili tanpa komplikasi', 'namainggris' => 'Measles without complication', ],
        	['code' => 'B07', 'namaindo' => 'Veruka vulgaris', 'namainggris' => 'Viral warts', ],
        	['code' => 'B08.1', 'namaindo' => 'Moluskum kontagiosum', 'namainggris' => 'Molluscum contagiosum', ],
        	['code' => 'B15', 'namaindo' => 'Hepatitis A', 'namainggris' => 'Hepatitis A', ],
        	['code' => 'B16', 'namaindo' => 'Hepatitis B', 'namainggris' => 'Acute hepatitis B', ],
        	['code' => 'B20', 'namaindo' => 'HIV AIDS tanpa komplikasi', 'namainggris' => 'Human immunodeficiency virus [HIV] disease', ],
        	['code' => 'B26', 'namaindo' => 'Parotitis', 'namainggris' => 'Mumps', ],
        	['code' => 'B35.0', 'namaindo' => 'Tinea kapitis', 'namainggris' => 'Tinea barbae and tinea capitis', ],
        	['code' => 'B35.0', 'namaindo' => 'Tinea barbae', 'namainggris' => 'Tinea barbae and tinea capitis', ],
        	['code' => 'B35.1', 'namaindo' => 'Tinea unguium', 'namainggris' => 'Tinea unguium', ],
        	['code' => 'B35.2', 'namaindo' => 'Tinea manum', 'namainggris' => 'Tinea manuum', ],
        	['code' => 'B35.3', 'namaindo' => 'Tinea pedis', 'namainggris' => 'Tinea pedis', ],
        	['code' => 'B35.4', 'namaindo' => 'Tinea korporis', 'namainggris' => 'Tinea corporis', ],
        	['code' => 'B35.6', 'namaindo' => 'Tinea kruris', 'namainggris' => 'Tinea cruris', ],
        	['code' => 'B35.8', 'namaindo' => 'Tinea fasialis', 'namainggris' => 'Other dermatophytoses', ],
        	['code' => 'B36.0', 'namaindo' => 'Pitiriasis versikolor', 'namainggris' => 'Pityriasis versicolor', ],
        	['code' => 'B37.0', 'namaindo' => 'Kandidiasis mulut', 'namainggris' => 'Candidal stomatitis', ],
        	['code' => 'B50-B54', 'namaindo' => 'Malaria', 'namainggris' => 'Malaria', ],
        	['code' => 'B65.0', 'namaindo' => 'Skistosomiasis', 'namainggris' => 'Schistosomiasis', ],
        	['code' => 'B68.0', 'namaindo' => 'Taeniasis', 'namainggris' => 'Taeniasis', ],
        	['code' => 'B74', 'namaindo' => 'Filariasis', 'namainggris' => 'Filariasis', ],
        	['code' => 'B76.0', 'namaindo' => 'Penyakit cacing tambang', 'namainggris' => 'Ancylostomiasis', ],
        	['code' => 'B76.9', 'namaindo' => 'Cutaneus larva migran', 'namainggris' => 'Hookworm disease, unspecified', ],
        	['code' => 'B77', 'namaindo' => 'Askariasis', 'namainggris' => 'Ascariasis', ],
        	['code' => 'B78', 'namaindo' => 'Strongiloidiasis', 'namainggris' => 'Strongyloidiasis', ],
        	['code' => 'B85', 'namaindo' => 'Pedikulosis kapitis', 'namainggris' => 'Pediculosis', ],
        	['code' => 'B86', 'namaindo' => 'Skabies', 'namainggris' => 'Scabies', ],
        	['code' => 'D17', 'namaindo' => 'Lipoma', 'namainggris' => 'Lipomatous', ],
        	['code' => 'D50', 'namaindo' => 'Anemia defisiensi besi', 'namainggris' => 'Iron deficiency anemia', ],
        	['code' => 'E05.00', 'namaindo' => 'Tirotoksikosis', 'namainggris' => 'Thyrotoxicosis', ],
        	['code' => 'E10', 'namaindo' => 'Diabetes melitus tipe 1', 'namainggris' => 'Type 1 diabetes mellitus', ],
        	['code' => 'E11', 'namaindo' => 'Diabetes melitus tipe 2', 'namainggris' => 'Type 2 diabetes mellitus', ],
        	['code' => 'E16', 'namaindo' => 'Hipoglikemia ringan', 'namainggris' => 'Hypoglycemia', ],
        	['code' => 'E64.0', 'namaindo' => 'Malnutiris energi-protein', 'namainggris' => 'Sequelae of protein-calorie malnutrition', ],
        	['code' => 'E66', 'namaindo' => 'Obesitas', 'namainggris' => 'Overweight and obesity', ],
        	['code' => 'E78', 'namaindo' => 'Dislipidemia', 'namainggris' => 'Disorders of lipoprotein metabolism and other lipidemias', ],
        	['code' => 'E79.0', 'namaindo' => 'Hiperuricemia (Gout)', 'namainggris' => 'Hyperuricemia', ],
        	['code' => 'F01-F03', 'namaindo' => 'Demensia', 'namainggris' => 'Dementia', ],
        	['code' => 'F05', 'namaindo' => 'Delirium yang diinduksi dan tidak diinduksi oleh alkohol atau zat psikoaktif lainnya', 'namainggris' => 'Delirium due to known physiological condition', ],
        	['code' => 'F23-F24', 'namaindo' => 'Gangguan psikotik', 'namainggris' => 'psychotic disorder', ],
        	['code' => 'F41.3', 'namaindo' => 'Gangguan campuran anxietas dan depresi', 'namainggris' => 'Other mixed anxiety disorders', ],
        	['code' => 'G40', 'namaindo' => 'Epilepsi', 'namainggris' => 'Epilepsy and recurrent seizures', ],
        	['code' => 'G40.901', 'namaindo' => 'Status Epileptikus', 'namainggris' => 'Epilepsy with status epilepticus', ],
        	['code' => 'G43', 'namaindo' => 'Migren', 'namainggris' => 'Migraine', ],
        	['code' => 'G44.201', 'namaindo' => 'Tension headache', 'namainggris' => 'Tension-type headache', ],
        	['code' => 'G47.0', 'namaindo' => 'Insomnia', 'namainggris' => 'Insomnia', ],
        	['code' => 'G51.0', 'namaindo' => 'Bell’s Palsy', 'namainggris' => 'Bell’s palsy', ],
        	['code' => 'H00.01', 'namaindo' => 'Hordeolum', 'namainggris' => 'Hordeolum', ],
        	['code' => 'H01.0', 'namaindo' => 'Blefaritis', 'namainggris' => 'Blepharitis', ],
        	['code' => 'H04', 'namaindo' => 'Mata kering', 'namainggris' => 'Dry eye', ],
        	['code' => 'H10', 'namaindo' => 'Konjungtivitis', 'namainggris' => 'Conjunctivitis', ],
        	['code' => 'H11.3', 'namaindo' => 'Perdarahan subkonjungtiva', 'namainggris' => 'Subconjunctival hemorrhage', ],
        	['code' => 'H26', 'namaindo' => 'Katarak', 'namainggris' => 'Cataract', ],
        	['code' => 'H40', 'namaindo' => 'Glaukoma akut', 'namainggris' => 'Glaucoma', ],
        	['code' => 'H52.0', 'namaindo' => 'Hipermetropia ringan', 'namainggris' => 'Hypermetropia', ],
        	['code' => 'H52.1', 'namaindo' => 'Miopia ringan', 'namainggris' => 'Myopia', ],
        	['code' => 'H52.2', 'namaindo' => 'Astigmatism ringan', 'namainggris' => 'Astigmatism', ],
        	['code' => 'H52.4', 'namaindo' => 'Presbiopia', 'namainggris' => 'Presbyopia', ],
        	['code' => 'H53.6', 'namaindo' => 'Buta senja', 'namainggris' => 'Night blindness', ],
        	['code' => 'H60', 'namaindo' => 'Otitis eksterna', 'namainggris' => 'Otitis externa', ],
        	['code' => 'H61.2', 'namaindo' => 'Serumen prop', 'namainggris' => 'Impacted cerumen', ],
        	['code' => 'H65', 'namaindo' => 'Otitis media akut', 'namainggris' => 'Otitis media', ],
        	['code' => 'H81.10', 'namaindo' => 'Vertigo (Benign paroxysmal positional vertigo)', 'namainggris' => 'Benign paroxysmal vertigo', ],
        	['code' => 'I10', 'namaindo' => 'Hipertensi esensial', 'namainggris' => 'Essential (primary) hypertension', ],
        	['code' => 'I20', 'namaindo' => 'Angina pektoris', 'namainggris' => 'Angina pectoris', ],
        	['code' => 'I21.9', 'namaindo' => 'Infark miokard', 'namainggris' => 'Acute myocardial infarction', ],
        	['code' => 'I46', 'namaindo' => 'Cardiorespiratory arrest', 'namainggris' => 'Cardiac arrest', ],
        	['code' => 'I50.21', 'namaindo' => 'Gagal jantung akut', 'namainggris' => 'Acute systolic (congestive) heart failure', ],
        	['code' => 'I50.22', 'namaindo' => 'Gagal jantung kronik', 'namainggris' => 'Chronic systolic (congestive) heart failure', ],
        	['code' => 'I63.9', 'namaindo' => 'Infark serebral/ Stroke', 'namainggris' => 'Cerebral infarction', ],
        	['code' => 'J02', 'namaindo' => 'Faringitis', 'namainggris' => 'Acute pharyngitis', ],
        	['code' => 'J03', 'namaindo' => 'Tonsilitis', 'namainggris' => 'Acute tonsillitis', ],
        	['code' => 'J04.0', 'namaindo' => 'Laringitis', 'namainggris' => 'Acute laryngitis', ],
        	['code' => 'J11.81', 'namaindo' => 'Influenza', 'namainggris' => 'Influenza', ],
        	['code' => 'J18', 'namaindo' => 'Pneumonia aspirasi', 'namainggris' => 'Pneumonia, unspecified organism', ],
        	['code' => 'J19', 'namaindo' => 'Pneumonia, bronkopneumonia', 'namainggris' => 'Pneumonia', ],
        	['code' => 'J20', 'namaindo' => 'Bronkritis akut', 'namainggris' => 'Acute bronchitis', ],
        	['code' => 'J30', 'namaindo' => 'Rhinitis akut', 'namainggris' => 'Acute rhinitis', ],
        	['code' => 'J30.0', 'namaindo' => 'Rhinitis vasomotor', 'namainggris' => 'Vasomotor rhinitis', ],
        	['code' => 'J30.8', 'namaindo' => 'Rhinitis alergika', 'namainggris' => 'Other allergic rhinitis', ],
        	['code' => 'J34.0', 'namaindo' => 'Furunkel pada hidung', 'namainggris' => 'Abscess, furuncle and carbuncle of nose', ],
        	['code' => 'J45', 'namaindo' => 'Asma Bronkial', 'namainggris' => 'Asthma', ],
        	['code' => 'K21.9', 'namaindo' => 'Refluks gastroesofageal', 'namainggris' => 'Gastro-esophageal reflux disease without esophagitis', ],
        	['code' => 'K29', 'namaindo' => 'Gastritis', 'namainggris' => 'Gastritis and duodenitis', ],
        	['code' => 'K35', 'namaindo' => 'Apendisitis akut', 'namainggris' => 'Acute appendicitis', ],
        	['code' => 'K64', 'namaindo' => 'Hemoroid grade 1-2', 'namainggris' => 'Hemorrhoids and perianal venous thrombosis', ],
        	['code' => 'K65', 'namaindo' => 'Peritonitis', 'namainggris' => 'Peritonitis', ],
        	['code' => 'K81', 'namaindo' => 'Kolesistitis', 'namainggris' => 'Cholecystitis', ],
        	['code' => 'K90.49', 'namaindo' => 'Malabsorbsi makanan', 'namainggris' => 'Malabsorption due to intolerance', ],
        	['code' => 'L04', 'namaindo' => 'Limfadenitis', 'namainggris' => 'Acute lymphadenitis', ],
        	['code' => 'L08.0', 'namaindo' => 'Pioderma', 'namainggris' => 'Pyoderma', ],
        	['code' => 'L20', 'namaindo' => 'Dermatitis atopik (kecuali recalcitrant )', 'namainggris' => 'Atopic dermatitis', ],
        	['code' => 'L21', 'namaindo' => 'Dermatitis seboroik', 'namainggris' => 'Seborrheic dermatitis', ],
        	['code' => 'L22', 'namaindo' => 'Napkin eczema', 'namainggris' => 'Diaper dermatitis', ],
        	['code' => 'L23', 'namaindo' => 'Dermatitis kontak alergika', 'namainggris' => 'Allergic contact dermatitis', ],
        	['code' => 'L24', 'namaindo' => 'Dermatitis kontak iritan', 'namainggris' => 'Irritant contact dermatitis', ],
        	['code' => 'L27.0', 'namaindo' => 'Exanthematous drug eruption', 'namainggris' => 'Generalized skin eruption due to drugs and medicaments taken internally', ],
        	['code' => 'L27.1', 'namaindo' => 'Fixed drug eruption', 'namainggris' => 'Localized skin eruption due to drugs and medicaments taken internally', ],
        	['code' => 'L28.0', 'namaindo' => 'Liken simpleks kronis/ neurodermatitis', 'namainggris' => 'Lichen simplex chronicus', ],
        	['code' => 'L30.0', 'namaindo' => 'Dermatitis numularis', 'namainggris' => 'Nummular dermatitis', ],
        	['code' => 'L42', 'namaindo' => 'Pitiriasis rosea', 'namainggris' => 'Pityriasis rosea', ],
        	['code' => 'L50.1', 'namaindo' => 'Urtikaria (akut dan kronis)', 'namainggris' => 'Idiopathic urticaria', ],
        	['code' => 'L74', 'namaindo' => 'Miliaria', 'namainggris' => 'Miliaria', ],
        	['code' => 'M05', 'namaindo' => 'Artritis Reumatoid', 'namainggris' => 'Rheumatoid arthritis with rheumatoid factor', ],
        	['code' => 'M15-M19', 'namaindo' => 'Artritis Osteoartritis', 'namainggris' => 'Osteoarthritis', ],
        	['code' => 'M35.3', 'namaindo' => 'Polimialgia reumatik', 'namainggris' => 'Polymyalgia rheumatica', ],
        	['code' => 'N39.0', 'namaindo' => 'Infeksi saluran kemih', 'namainggris' => 'Urinary tract infection', ],
        	['code' => 'N61.0', 'namaindo' => 'Mastitis', 'namainggris' => 'Mastitis without abscess', ],
        	['code' => 'N76.0', 'namaindo' => 'Vaginitis', 'namainggris' => 'Acute vaginitis', ],
        	['code' => 'N76.2', 'namaindo' => 'Vulvitis', 'namainggris' => 'Acute vulvitis', ],
        	['code' => 'N89.8', 'namaindo' => 'Fluor albus/vaginal discharge non gonorhea', 'namainggris' => 'Other specified noninflammatory disorders of vagina', ],
        	['code' => 'N90', 'namaindo' => 'Ruptur perineum tingkat 1-2', 'namainggris' => 'Other noninflammatory disorders of vulva and perineum', ],
        	['code' => 'O03', 'namaindo' => 'Abortus spontan komplit', 'namainggris' => 'Spontaneous abortion', ],
        	['code' => 'O03.3', 'namaindo' => 'Abortus spontan inkomplit', 'namainggris' => 'Other and unspecified complications following incomplete spontaneous abortion', ],
        	['code' => 'O03.4', 'namaindo' => 'Abortus spontan inkomplit', 'namainggris' => 'Incomplete spontaneous abortion without complication', ],
        	['code' => 'O14', 'namaindo' => 'Pre-eklampsia', 'namainggris' => 'Pre-eclampsia', ],
        	['code' => 'O15', 'namaindo' => 'Eklampsia', 'namainggris' => 'Eclampsia', ],
        	['code' => 'O20.0', 'namaindo' => 'Abortus mengancam/insipiens', 'namainggris' => 'Threatened abortion', ],
        	['code' => 'O21.0', 'namaindo' => 'Hiperemesis gravidarum', 'namainggris' => 'Mild hyperemesis gravidarum', ],
        	['code' => 'O42.01', 'namaindo' => 'Ketuban Pecah Dini (KPD)', 'namainggris' => 'Preterm premature rupture of membranes, onset of labor within 24 hours of rupture', ],
        	['code' => 'O63', 'namaindo' => 'Persalinan lama', 'namainggris' => 'Prolonged labor', ],
        	['code' => 'O72', 'namaindo' => 'Perdarahan post partum', 'namainggris' => 'Postpartum hemorrhage', ],
        	['code' => 'O99.019', 'namaindo' => 'Anemia defisiensi besi pada kehamilan', 'namainggris' => 'Iron deficiency anemia in pregnancy', ],
        	['code' => 'P38', 'namaindo' => 'Infeksi pada umbilikus', 'namainggris' => 'Omphalitis', ],
        	['code' => 'R00.0', 'namaindo' => 'Takikardi', 'namainggris' => 'Tachycardia, unspecified', ],
        	['code' => 'R04.0', 'namaindo' => 'Epistaksis', 'namainggris' => 'Epistaxis', ],
        	['code' => 'R56.00', 'namaindo' => 'Kejang demam', 'namainggris' => 'Simple febrile convulsions', ],
        	['code' => 'R57.9', 'namaindo' => 'Syok (septik), hipovolemik, kardiogenik, neurogenik)', 'namainggris' => 'Shock, unspecified', ],
        	['code' => 'R73.0', 'namaindo' => 'Hiperglikemi hiperosmolar non ketotik', 'namainggris' => 'Hyperglycemia', ],
        	['code' => 'T15.1', 'namaindo' => 'Benda asing di konjungtiva', 'namainggris' => 'Foreign body in conjunctival sac', ],
        	['code' => 'T17.1', 'namaindo' => 'Benda asing di hidung', 'namainggris' => 'Foreign body in nostril', ],
        	['code' => 'T20-T25', 'namaindo' => 'Luka bakar derajat 1 dan 2', 'namainggris' => 'Burn', ],
        	['code' => 'T50.A1', 'namaindo' => 'Pertusis', 'namainggris' => 'Pertussis', ],
        	['code' => 'T62.94XA', 'namaindo' => 'Keracunan makanan', 'namainggris' => 'Toxic effect of unspecified noxious substance eaten as food, undetermined, initial encounter', ],
        	['code' => 'T78', 'namaindo' => 'Reaksi anafilaktik', 'namainggris' => 'Anaphylactic reaction', ],
        	['code' => 'T78.0', 'namaindo' => 'Intoleransi makanan', 'namainggris' => 'Anaphylactic reaction due to food', ],
        	['code' => 'Z34.01', 'namaindo' => 'Kehamilan normal', 'namainggris' => 'Encounter for supervision of normal first pregnancy, first trimester', ],
        	['code' => 'Z91.01', 'namaindo' => 'Alergi makanan', 'namainggris' => 'Food allergy status', ],
        ];

        Disease::insert($data);
    }
}
